### ISSUE TITLE
Issue #1: User can search for a card

### ISSUE THREAD

**Issue by SharjeelSIqbal** [SharjeelSIqbal/shadow-deck#1]
## ⚙️ Feature

User can view cards

## 📐 Functionality

User will be able to look at his or her cards in the main screen, if he/she has any. If not, it will inform the user the build a new deck. 

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/50930123/127197555-1bfff9a6-322b-4ddf-a79a-a9228b2eda01.png)
![image](https://user-images.githubusercontent.com/50930123/127200722-3b9d7a6c-adad-4657-b807-505f1fcd71fa.png)
![image](https://user-images.githubusercontent.com/50930123/127200761-3637e64a-4c0e-4c61-8e12-ba1aab38411f.png)
![image](https://user-images.githubusercontent.com/50930123/127200984-2fa79280-8fe4-47cb-a0cf-3ebac39958be.png)

![image](https://user-images.githubusercontent.com/50930123/127197595-54097751-32ce-4d2f-b151-b86e145cdbdb.png)
![image](https://user-images.githubusercontent.com/50930123/127201269-40f2ef30-a50f-4739-9924-6aaea07bf4f8.png)

## ✅ Task List

- [x] Create media queries for phone formats.
- [x] Add a unique identifier to the deck.
- [x] Create a new element with the class hidden and css property display with the value of hidden.
- [x] When user clicks on new deck a search bar will appear.
- [x]  Add a nav bar with two views search and my deck (desktop).
- [x] Create a div that contains the deck icon (desktop).
- [x] Create label for "New Deck" attaching it to the div above (desktop).
- [x] When clicked on "New Deck" it will take user to the search page otherwise it will remain on the main page displaying cards if the user has any. (desktop).
- [x] When user types in the card name, different cards with that name will appear in the console.
 - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
  - [x] Send to Cody for approval.
