### ISSUE TITLE
Issue #5: User can delete cards from deck

### ISSUE THREAD

**Issue by SharjeelSIqbal** [SharjeelSIqbal/shadow-deck#10]
## ⚙️ Feature

User will be able to remove cards from his/her deck
## 📐 Functionality

User will click on the card he/she wants to remove and a modal will pop up asking if they'd like to remove the card and once they click confirm they will be able to remove that card or if they press cancel return to the same screen
## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/50930123/128232189-a571f13d-61f2-4f7d-bf21-15d045aa238a.png)
![image](https://user-images.githubusercontent.com/50930123/128232228-c0b729b9-3631-4080-b028-7450b6f885df.png)

## ✅ Task List

- [x] Add an event listener that occurs within the deck 
- [x] The event listener will be looking for clicks on images and once clicked on that image it will ask if the user would like to remove the card 
- [x] Once clicked confirm remove the index from the card deck and the image from the deck-view and update the card count 
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
