### ISSUE TITLE
Issue #6: User can create multiple decks

### ISSUE THREAD

**Issue by SharjeelSIqbal** [SharjeelSIqbal/shadow-deck#19]
## ⚙️ Feature
User will be able to create multiple and view them
## 📐 Functionality
User will be able to create multiple decks and be able to view them;
## 🖼️ Wireframes
![image](https://user-images.githubusercontent.com/50930123/128963767-25f51359-242c-4da8-9ce6-df6ff7098a1c.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Reappend new deck on to the page with just the placeholder image. When new deck the page will take you to a blank my deck. 
- [ ] Append the new deck into index.html  as well as any existing decks 
- [ ] Automatically the first deck the user has created should be appended so that when my deck is clicked it will show results for the first deck or the last deck the user had accessed appears
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
