### ISSUE TITLE
Issue #2: User can view cards

### ISSUE THREAD

**Issue by SharjeelSIqbal** [SharjeelSIqbal/shadow-deck#3]
## ⚙️ Feature

User can view cards

## 📐 Functionality

When user will now be able to see his search results appear in front of him. 

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/50930123/127405980-2956d3c7-a10d-4b6d-833c-5e898e5cf5fb.png)
![image](https://user-images.githubusercontent.com/50930123/127409162-fe815e3a-52eb-4bf0-a73a-4deb9ff3c0fb.png)

## ✅ Task List

- [x] Append images of search objects to the page
- [x] Limit the number of images appended on the visible page
- [x] Keep a counter on top referring to what page it's currently on and how many cards the user has seen and how many are left eg: page 1: 0-20  2: 40-60  3: 60-64
- [x] When the images search bar is reset or changed then remove all images and add new ones according the keywords of the search input
- [x] When user clicks next page the page increments by +1
- [x] When user clicks prev page the page increments by -1
- [x] When images appear create a hover style to scale the image up a little bit 
- [x] When the image scales up it should transition to make it more organic
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
  - [x] Send to Cody for review
