### ISSUE TITLE
Issue #3: User can add card to deck

### ISSUE THREAD

**Issue by SharjeelSIqbal** [SharjeelSIqbal/shadow-deck#6]
## ⚙️ Feature

User can add card to deck

## 📐 Functionality

User will be able to click on a card and add a card to deck

## 🖼️ Wireframes
![image](https://user-images.githubusercontent.com/50930123/127571870-a5ea487d-23ab-4fd7-98dd-e2b4e3989614.png)
![image](https://user-images.githubusercontent.com/50930123/127571904-247477eb-6d4e-4824-932c-308c510e3191.png)

## ✅ Task List
- [x] Create a data model that holds card information
- [x] Data model should be able to store multiple decks if needed
- [x] When user clicks on new deck icon it should store value of deck 1 in to the data model
- [x] When user clicks on a card, a modal will pop up with a question asking if they want to add the card to the deck
- [x] When a user adds a card to the deck the card should store all information (not just image) into the data model 
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
