### ISSUE TITLE
Issue #4: User can view deck

### ISSUE THREAD

**Issue by SharjeelSIqbal** [SharjeelSIqbal/shadow-deck#8]
## ⚙️ Feature

User can view deck.

## 📐 Functionality

When user adds cards to the deck it will now appear in the deck view. 

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/50930123/127717555-c208339e-be94-4d0a-9c29-8acca4955132.png)
![image](https://user-images.githubusercontent.com/50930123/127717566-940e33a8-38f7-4db2-9166-40ad141ebc78.png)

## ✅ Task List

- [x] Create a local storage variable that will store data
- [x] Get card images from local storage and append it to the deck-view element
- [x] The number should increment each time a card is added
- [x] Make it so the data.decks[0].cards does not exceed more than 50 total index's 
- [x] Create a placeholder image for the deck with the strongest attack points to represent the deck
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
